apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: baejw-reg
          image: baejw-reg.kr.ncr.ntruss.com/test:10.0
          ports:
            - containerPort: 8000
